version: '3'
services:
  redis:
    image: redis
    container_name: redis.cnab
  db:
    image: postgres
    volumes:
      - ./backend/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    container_name: postgres.cnab
  web:
    build: ./backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    container_name: api.cnab
  sidekiq:
    build: ./backend
    command: bundle exec sidekiq
    volumes:
      - ./backend:/myapp
    depends_on:
      - db
      - redis
    container_name: sidekiq.cnab
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin:/root/.pgadmin
    depends_on:
      - db
    container_name: pgadmin.cnab
  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    container_name: frontend.cnab
volumes:
  pgadmin:
